language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 6.7

install:
  - npm install

script:
  - npm run build
  - npm run link
  - cd example/koa-service
  - npm link roc-plugin-dredd
  - npm install
  - npm run build
  - npm run dredd
  - cat report.xml

after_success:
  - npm start docs
